DROP TABLE IF EXISTS `user_role`;
DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS `role`;

CREATE TABLE `user` (
  `ID` int(10) unsigned NOT NULL,
  `EMAIL` varchar(45) NOT NULL,
  `PASSWORD` varchar(45) NOT NULL,
  `FIRST_NAME` varchar(45) DEFAULT NULL,
  `LAST_NAME` varchar(45) DEFAULT NULL,
  `IS_DELETED` tinyint(4) DEFAULT NULL,
  `CREATED_DATE_EPOCH` bigint(20) DEFAULT NULL,
  `MODIFIED_DATE_EPOCH` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `role` (
  `ID` int(10) unsigned NOT NULL,
  `COMMENT` varchar(45) DEFAULT NULL,
  `CREATED_DATE_EPOCH` bigint(20) DEFAULT NULL,
  `MODIFIED_DATE_EPOCH` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `user_role` (
  `ID` int(10) unsigned NOT NULL,
  `USER_ID` int(10) unsigned DEFAULT NULL,
  `ROLE_ID` int(10) unsigned DEFAULT NULL,
  `CREATED_DATE_EPOCH` bigint(20) DEFAULT NULL,
  `MODIFIED_DATE_EPOCH` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `fk_user_id_idx` (`USER_ID`),
  KEY `fk_role_id_idx` (`ROLE_ID`),
  CONSTRAINT `fk_user` FOREIGN KEY (`USER_ID`) REFERENCES `user` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_role` FOREIGN KEY (`ROLE_ID`) REFERENCES `role` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
